export const  FAVT_REQUEST_PENDING="FAVT_REQUEST_PENDING"
export const  FAVT_REQUEST_SUCCESS="FAVT_REQUEST_SUCCESS"
export const  FAVT_REQUEST_REMOVE="FAVT_REQUEST_REMOVE"
export const  FAVT_REQUEST_FAILURE="FAVT_REQUEST_FAILURE"